### ISSUE TITLE
run in CuteChess and on Linux ?

### ISSUE THREAD

**Issue by tissatussa** [Alex2262/Antares#3]
in the README you state :

> Antares doesn't work with Cutechess due to long initialization times.

indeed, CuteChess can not initialise the engine :

`Engine Error .. no response to ping`

however, when executing `python3 ./main.py` in terminal, i get a quick response after the `uci` command and immediately i can give the command `ucinewgame` and let the engine think by `go depth [#]` :

```
$ python3 ./main.py 
uci
>>> uci
id name AntaresPy0.47
id author Alexander_Tian
uciok
ucinewgame
>>> ucinewgame
go depth 6
>>> go depth 6
info depth 1 score cp 54 time 0 nodes 21 nps 118228 pv b1c3
info depth 2 score cp 8 time 0 nodes 81 nps 151398 pv b1c3 b8c6
info depth 3 score cp 53 time 1 nodes 252 nps 214047 pv b1c3 b8c6 g1f3
info depth 4 score cp 8 time 4 nodes 1092 nps 253595 pv b1c3 b8c6 g1f3 g8f6
info depth 5 score cp 41 time 8 nodes 2212 nps 262529 pv b1c3 b8c6 g1f3 g8f6 e2e4
bestmove b1c3
```

this seems to work .. so why does CuteChess fail?
Note: i see an 'echo' of my commands by '>>>' .. why? CuteChess might not like that either ..

> There is a release for windows in the dist folder.

i'm on Linux Xubuntu 22.04, so i'm not able to use that binary .. how did you compile it? Can this be done on Linux also?

**Comment by Alex2262** [comment]
Hi Tissatussa, the reason that there are these 'long initialization times' is because I am using numba with python to JIT compile it. This JIT compilation takes around 5-20 seconds depending on the computer when first starting the engine. When you input `uci` and the regular commands into Antares, it will respond normally. However, if you enter a command to search such as `go` before it has completed initializing, then the engine may malfunction. This is why it's needed to pass `isready` and wait for the engine to respond with `readyok`. However, if you pass `isready` or `go` after the initialize time has ended, then it will work normally as the engine has already initialized. The reason it doesn't work with cutechess is because cutechess only allows an around 10 second initialization time for the engine, and Antares may take longer than that allotted Time. It can be confusing to deal with this engine, so you may want to checkout Altair it is in my github repositories. It is the successor of this engine in c++, so it doesn't have issues with initialization times. Also you noted the echo with '>>>' this is used for debugging, but cutechess shouldn't have problems with it. To compile it, you can install python and then download `pip`. Then do `pip install pyinstaller`. Then cd Antares. Then `pyinstaller main.py --onefile` This will create a dist folder in the folder of the engine, and then an executable of the engine will be inside.

**Comment by tissatussa** [comment]
Thanks for the info .. it's clear .. i managed to compile a binary (called 'main') in the dist folder. It runs fine in terminal but CuteChess still has init problems : protocol takes too long .. i'm fine with the binary though - thanks for that, and pointing me to 'pyinstaller' .. it seems to work well, i had no single error or warning (but a few years ago i had problems with pyinstaller). Could Cython be an alternative ?

**Comment by Alex2262** [comment]
Hi yeah. That’s why I stopped working on it because the Numba JIT compiler for python was too hard to deal with. I think Cython would have been better, but now I’m using C++ so I don’t feel like switching anymore.
